Somativa/Somativa/Models/VendaItem.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Somativa.Models
{
    public class VendaItem
    {
        public Guid VendaItemId { get; set; }
        [DisplayName("Nota Fiscal")]
        [Required(ErrorMessage = "O Campo Nota Fiscal Está Inválido!!!")]

        public Guid VendaId { get; set; }
        public Venda? Venda { get; set; }
        [DisplayName("Produto")]
        [Required(ErrorMessage = "O Campo Produto Está Inválido!!!")]

        public Guid ProdutoId { get; set; }
        public Produto? Produto { get; set; }
        [Required(ErrorMessage = "O Campo Quantidade Está Inválido!!!")]

        public int Quantidade { get; set; }
        [Required(ErrorMessage = "O Campo Unitário Está Inválido!!!")]

        public decimal Unitario { get; set; }
    }
}

Somativa/Somativa/Controllers/VendaItemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Somativa.Data;
using Somativa.Models;

namespace Somativa.Controllers
{
	[Authorize(Roles = "Admin,Operador")]
	public class VendaItemsController : Controller
    {
        private readonly SprintContext _context;

        public VendaItemsController(SprintContext context)
        {
            _context = context;
        }

        // GET: VendaItems
        public async Task<IActionResult> Index(Guid Id)
        {
            var sprintContext = _context.VendaItens.Include(v => v.Produto).Include(v => v.Venda);
            ViewData["VendaId"] =  Id ;
            return View(await sprintContext.Where(i => i.VendaId==Id).ToListAsync());
        }

        // GET: VendaItems/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null || _context.VendaItens == null)
            {
                return NotFound();
            }

            var vendaItem = await _context.VendaItens
                .Include(v => v.Produto)
                .Include(v => v.Venda)
                .FirstOrDefaultAsync(m => m.VendaItemId == id);
            if (vendaItem == null)
            {
                return NotFound();
            }

            return View(vendaItem);
        }

        // GET: VendaItems/Create
        public IActionResult Create(Guid Id)
        {
            ViewData["ProdutoId"] = new SelectList(_context.Produtos, "ProdutoId", "Nome");
            
            //ViewData["VendaId"] = new SelectList(_context.Vendas, "VendaId", "Nome");
            ViewData["VendaId"] = Id;          
            return View();
        }

        // POST: VendaItems/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("VendaItemId,VendaId,ProdutoId,Quantidade,Unitario")] VendaItem vendaItem)
        {
            if (ModelState.IsValid)
            {
                vendaItem.VendaItemId = Guid.NewGuid();
                _context.Add(vendaItem);
                await _context.SaveChangesAsync();

                Produto p = _context.Produtos.Where(p => p.ProdutoId == vendaItem.ProdutoId).FirstOrDefault();
                p.Estoque -= vendaItem.Quantidade;
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index), new {Id = vendaItem.VendaId});
            }
            ViewData["ProdutoId"] = new SelectList(_context.Produtos, "ProdutoId", "Nome", vendaItem.ProdutoId);
            ViewData["VendaId"] = new SelectList(_context.Vendas, "VendaId", "Nota", vendaItem.VendaId);
                      

            return View(vendaItem);
        }

        // GET: VendaItems/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null || _context.VendaItens == null)
            {
                return NotFound();
            }

            var vendaItem = await _context.VendaItens.FindAsync(id);
            if (vendaItem == null)
            {
                return NotFound();
            }
            ViewData["ProdutoId"] = new SelectList(_context.Produtos, "ProdutoId", "Nome", vendaItem.ProdutoId);
            ViewData["VendaId"] = new SelectList(_context.Vendas, "VendaId", "Nota", vendaItem.VendaId);
            return View(vendaItem);
        }

        // POST: VendaItems/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("VendaItemId,VendaId,ProdutoId,Quantidade,Unitario")] VendaItem vendaItem)
        {
            if (id != vendaItem.VendaItemId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(vendaItem);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VendaItemExists(vendaItem.VendaItemId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ProdutoId"] = new SelectList(_context.Produtos, "ProdutoId", "Nome", vendaItem.ProdutoId);
            ViewData["VendaId"] = new SelectList(_context.Vendas, "VendaId", "Nota", vendaItem.VendaId);
            return View(vendaItem);
        }

        // GET: VendaItems/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null || _context.VendaItens == null)
            {
                return NotFound();
            }

            var vendaItem = await _context.VendaItens
                .Include(v => v.Produto)
                .Include(v => v.Venda)
                .FirstOrDefaultAsync(m => m.VendaItemId == id);
            if (vendaItem == null)
            {
                return NotFound();
            }

            return View(vendaItem);
        }

        // POST: VendaItems/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            if (_context.VendaItens == null)
            {
                return Problem("Entity set 'SprintContext.VendaItens'  is null.");
            }
            var vendaItem = await _context.VendaItens.FindAsync(id);
            if (vendaItem != null)
            {
                _context.VendaItens.Remove(vendaItem);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool VendaItemExists(Guid id)
        {
          return (_context.VendaItens?.Any(e => e.VendaItemId == id)).GetValueOrDefault();
        }
    }
}

Somativa/Somativa/Controllers/VendasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Somativa.Data;
using Somativa.Models;

namespace Somativa.Controllers
{
	[Authorize(Roles = "Admin,Operador")]
	public class VendasController : Controller
    {
        private readonly SprintContext _context;

        public VendasController(SprintContext context)
        {
            _context = context;
        }

        // GET: Vendas
        public async Task<IActionResult> Index()
        {
            var sprintContext = _context.Vendas.Include(v => v.Cliente);
            return View(await sprintContext.ToListAsync());
        }

        // GET: Vendas/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null || _context.Vendas == null)
            {
                return NotFound();
            }

            var venda = await _context.Vendas
                .Include(v => v.Cliente)
                .FirstOrDefaultAsync(m => m.VendaId == id);
            if (venda == null)
            {
                return NotFound();
            }

            return View(venda);
        }

        // GET: Vendas/Create
        public IActionResult Create()
        {
            ViewData["ClienteId"] = new SelectList(_context.Clientes, "ClienteId", "Nome");
            return View();
        }

        // POST: Vendas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("VendaId,Nota,ClienteId,DataHora")] Venda venda)
        {
            if (ModelState.IsValid)
            {
                venda.VendaId = Guid.NewGuid();
                _context.Add(venda);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ClienteId"] = new SelectList(_context.Clientes, "ClienteId", "Nome", venda.ClienteId);
            return View(venda);
        }

        // GET: Vendas/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null || _context.Vendas == null)
            {
                return NotFound();
            }

            var venda = await _context.Vendas.FindAsync(id);
            if (venda == null)
            {
                return NotFound();
            }
            ViewData["ClienteId"] = new SelectList(_context.Clientes, "ClienteId", "Nome", venda.ClienteId);
            return View(venda);
        }

        // POST: Vendas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("VendaId,Nota,ClienteId,DataHora")] Venda venda)
        {
            if (id != venda.VendaId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(venda);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VendaExists(venda.VendaId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ClienteId"] = new SelectList(_context.Clientes, "ClienteId", "Nome", venda.ClienteId);
            return View(venda);
        }

        // GET: Vendas/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null || _context.Vendas == null)
            {
                return NotFound();
            }

            var venda = await _context.Vendas
                .Include(v => v.Cliente)
                .FirstOrDefaultAsync(m => m.VendaId == id);
            if (venda == null)
            {
                return NotFound();
            }

            return View(venda);
        }

        // POST: Vendas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            if (_context.Vendas == null)
            {
                return Problem("Entity set 'SprintContext.Vendas'  is null.");
            }
            var venda = await _context.Vendas.FindAsync(id);
            if (venda != null)
            {
                _context.Vendas.Remove(venda);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool VendaExists(Guid id)
        {
          return (_context.Vendas?.Any(e => e.VendaId == id)).GetValueOrDefault();
        }
    }
}

Somativa/Somativa/Views/VendaItems/Create.cshtml
@model Somativa.Models.VendaItem

@{
    ViewData["Title"] = "Create";
    var VendaIdAux = ViewData["VendaId"];
}

<div class="row d-flex justify-content-center my-3">
    <div class="rounded conted py-3 col-10 col-sm-6">
        <h4 class="text-center">Adicionar Item da Venda</h4>

        <div class="row d-flex justify-content-center m-2 m-sm-0">
            <div class="col-md-10">
                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group" style="display:none">
                        <label asp-for="VendaId" class="control-label textin"></label>
                        <input asp-for="VendaId" value="@VendaIdAux" class="form-control rounded-pill border-1 my-2" readonly />
                    </div>
                    <div class="form-group">
                        <label asp-for="ProdutoId" class="control-label textin"></label>
                        <select asp-for="ProdutoId" class="form-control rounded-pill border-1 my-2" asp-items="ViewBag.ProdutoId"></select>
                    </div>
                    <div class="form-group">
                        <label asp-for="Quantidade" class="control-label textin"></label>
                        <input asp-for="Quantidade" class="form-control rounded-pill border-1 my-2" />
                        <span asp-validation-for="Quantidade" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Unitario" class="control-label textin"></label>
                        <input asp-for="Unitario" type="number" class="form-control rounded-pill border-1 my-2" />
                        <span asp-validation-for="Unitario" class="text-danger"></span>
                    </div>
                    <div class="form-group d-flex justify-content-center">
                        <button type="submit" value="Create" class="adidi rounded-pill me-2 my-2">Cadastrar</button>
                        <a asp-action="Index" asp-route-id="@VendaIdAux" class="btn volt rounded-pill my-2">Cancelar</a>
                    </div>
                </form>
            </div>
        </div>

    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Somativa/Somativa/Views/VendaItems/Delete.cshtml
@model Somativa.Models.VendaItem

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>VendaItem</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Venda)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Venda.VendaId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Produto)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Produto.ProdutoId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Quantidade)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Quantidade)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Unitario)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Unitario)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="VendaItemId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Somativa/Somativa/Views/VendaItems/Details.cshtml
@model Somativa.Models.VendaItem

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>VendaItem</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Venda)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Venda.VendaId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Produto)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Produto.ProdutoId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Quantidade)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Quantidade)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Unitario)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Unitario)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.VendaItemId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Somativa/Somativa/Views/VendaItems/Edit.cshtml
@model Somativa.Models.VendaItem

@{
    ViewData["Title"] = "Edit";
}

<div class="row d-flex justify-content-center my-3">
    <div class="rounded conted py-3 col-10 col-sm-6">
        <h4 class="text-center">Atualizar Item da Venda</h4>

        <div class="row d-flex justify-content-center m-2 m-sm-0">
            <div class="col-md-10">
                <form asp-action="Edit">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="VendaItemId" />
                    <div class="form-group">
                        <label asp-for="VendaId" class="control-label textin"></label>
                        <select asp-for="VendaId" class="form-control rounded-pill border-1 my-2" asp-items="ViewBag.VendaId"></select>
                        <span asp-validation-for="VendaId" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="ProdutoId" class="control-label textin"></label>
                        <select asp-for="ProdutoId" class="form-control rounded-pill border-1 my-2" asp-items="ViewBag.ProdutoId"></select>
                        <span asp-validation-for="ProdutoId" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Quantidade" class="control-label textin"></label>
                        <input asp-for="Quantidade" class="form-control rounded-pill border-1 my-2" />
                        <span asp-validation-for="Quantidade" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Unitario" class="control-label textin"></label>
                        <input asp-for="Unitario" type="number" class="form-control rounded-pill border-1 my-2" />
                        <span asp-validation-for="Unitario" class="text-danger"></span>
                    </div>
                    <div class="form-group d-flex justify-content-center">
                        <button type="submit" value="Save" class="adidi rounded-pill me-2 my-2">Salvar</button>
                        <a asp-action="Index" asp-route-id="" class="btn volt rounded-pill my-2">Cancelar</a>
                    </div>
                </form>
            </div>
        </div>

    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Somativa/Somativa/Views/VendaItems/Index.cshtml
@model IEnumerable<Somativa.Models.VendaItem>

@{
    ViewData["Title"] = "Index";
}

<h1 class="textocima">Itens da Venda</h1>

<p>
    <a asp-action="Create" asp-route-id="@ViewBag.VendaId" class="btn adidi rounded-pill me-3">Adicionar</a>
    <a asp-action="Index" asp-controller="Vendas" class="volt rounded-circle pt-1 pb-2 px-2">
        <svg bootstrap-icon="ArrowLeft" width="24" height="24" class="text-dark"></svg>
    </a>
</p>

<table class="table">
    <thead>
        <tr class="d-flex"> 
            <th class="border-0 d-none d-sm-table-cell col-2"></th>
            <th class="col-3">
                @Html.DisplayNameFor(model => model.Venda)
            </th>
            <th class="col-3">
                @Html.DisplayNameFor(model => model.Produto)
            </th>
            <th class="col-3 col-sm-2">
                @Html.DisplayNameFor(model => model.Quantidade)
            </th>
            <th class="col-3 col-sm-2">
                @Html.DisplayNameFor(model => model.Unitario)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr class="d-flex">
                <td class="d-none d-sm-table-cell col-2">
                    <a asp-action="Edit" asp-route-id="@item.VendaItemId" class="text-decoration-none">
                        <svg bootstrap-icon="PencilSquare" width="24" height="24" class="text-dark me-2 my-2"></svg>
                    </a>
                    <a data-bs-toggle="modal" data-bs-target="#ModalTrash-@item.VendaItemId">
                        <svg bootstrap-icon="Trash" width="24" height="24" class="text-dark me-2 my-2"></svg>
                    </a>
                </td>
                <td class ="col-3">
                    @Html.DisplayFor(modelItem => item.Venda.Nota)
                </td>
                <td class="col-3">
                    @Html.DisplayFor(modelItem => item.Produto.Nome)
                </td>
                <td class="col-3 col-sm-2">
                    @Html.DisplayFor(modelItem => item.Quantidade)
                </td>
                <td class="col-3 col-sm-2">
                    @Html.DisplayFor(modelItem => item.Unitario)
                </td>
            </tr>
            <tr class="d-sm-none w-100 d-flex ">
                <td class="col-6 d-flex justify-content-center">
                    <a asp-action="Edit" asp-route-id="@item.VendaItemId">
                        <svg bootstrap-icon="PencilSquare" width="24" height="24" class="text-dark me-2 my-2"></svg>
                    </a>
                </td>
                <td class="col-6 pe-0 d-flex justify-content-center ">
                    <a data-bs-toggle="modal" data-bs-target="#ModalTrash-@item.VendaItemId">
                        <svg bootstrap-icon="Trash" width="24" height="24" class="text-dark me-2 my-2"></svg>
                    </a>
                </td>
            </tr>
            <div class="modal fade" id="ModalTrash-@item.VendaItemId" data-bs-keyboard="false" aria-labelledby="staticBackdropLabel" tabindex="-1" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered">
                    <div class="modal-content">
                        <div class="modal-header justify-content-center border-0">
                            <h5 class="modal-title text-center volt px-5 py-1 fs">Apagar</h5>
                        </div>
                        <div class="modal-body text-center border-0">
                            <p class="text-dark fs-3 fst-normal">Tem certeza que deseja apagar dados da @Html.DisplayFor(modelItem => item.Venda.Nota)?</p>
                        </div>
                        <div class="modal-footer d-flex justify-content-center border-0">
                            <form asp-action="Delete" asp-route-id="@item.VendaItemId" class="me-5">
                                <input type="hidden" asp-for="@item.VendaItemId" />
                                <button type="submit" class="btn apag text-white">Deletar</button>
                            </form>
                            <button data-bs-dismiss="modal" class="btn volt2 text-white">Cancelar</button>
                        </div>
                    </div>
                </div>
            </div>
        }
    </tbody>
</table>