Somativa/Somativa/Models/CompraItem.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;


namespace Somativa.Models
{
    public class CompraItem
    {
        public Guid CompraItemId { get; set; }
        [DisplayName("Nota Fiscal")]
        [Required(ErrorMessage = "O Campo Nota Fiscal Está Inválido!!!")]

        public Guid CompraId { get; set; }
        public Compra? Compra { get; set; }
        [DisplayName("Produto")]
        [Required(ErrorMessage = "O Campo Produto Está Inválido!!!")]

        public Guid ProdutoId { get; set; }
        public Produto? Produto { get; set; }
        [Required(ErrorMessage = "O Campo Quantidade Está Inválido!!!")]

        public int Quantidade { get; set; }
        [Required(ErrorMessage = "O Campo Unitário Está Inválido!!!")]

        public decimal Unitario { get; set; }
    }
}

Somativa/Somativa/Controllers/CompraItemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Somativa.Data;
using Somativa.Models;

namespace Somativa.Controllers
{
	[Authorize(Roles = "Admin,Operador")]
	public class CompraItemsController : Controller
    {
        private readonly SprintContext _context;

        public CompraItemsController(SprintContext context)
        {
            _context = context;
        }

        // GET: CompraItems
        public async Task<IActionResult> Index(Guid Id)
        {
            var sprintContext = _context.CompraItens.Include(c => c.Compra).Include(c => c.Produto);
            ViewData["CompraId"] = Id;
            return View(await sprintContext.Where(i => i.CompraId == Id).ToListAsync());
        }

        // GET: CompraItems/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null || _context.CompraItens == null)
            {
                return NotFound();
            }

            var compraItem = await _context.CompraItens
                .Include(c => c.Compra)
                .Include(c => c.Produto)
                .FirstOrDefaultAsync(m => m.CompraItemId == id);
            if (compraItem == null)
            {
                return NotFound();
            }

            return View(compraItem);
        }

        // GET: CompraItems/Create
        public IActionResult Create(Guid Id)
        {
            //ViewData["CompraId"] = new SelectList(_context.Compras, "CompraId", "CompraId");            
            ViewData["ProdutoId"] = new SelectList(_context.Produtos, "ProdutoId", "Nome");
            ViewData["CompraId"] = Id;
            return View();
        }

        // POST: CompraItems/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CompraItemId,CompraId,ProdutoId,Quantidade,Unitario")] CompraItem compraItem)
        {
            if (ModelState.IsValid)
            {
                compraItem.CompraItemId = Guid.NewGuid();
                _context.Add(compraItem);
                await _context.SaveChangesAsync();

                Produto p = _context.Produtos.Where(p => p.ProdutoId == compraItem.ProdutoId).FirstOrDefault();
                p.Estoque += compraItem.Quantidade;
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index), new { Id = compraItem.CompraId });
            }
            ViewData["CompraId"] = new SelectList(_context.Compras, "CompraId", "Nota", compraItem.CompraId);
            ViewData["ProdutoId"] = new SelectList(_context.Produtos, "ProdutoId", "Nome", compraItem.ProdutoId);
            return View(compraItem);
        }

        // GET: CompraItems/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null || _context.CompraItens == null)
            {
                return NotFound();
            }

            var compraItem = await _context.CompraItens.FindAsync(id);
            if (compraItem == null)
            {
                return NotFound();
            }
            ViewData["CompraId"] = new SelectList(_context.Compras, "CompraId", "Nota", compraItem.CompraId);
            ViewData["ProdutoId"] = new SelectList(_context.Produtos, "ProdutoId", "Nome", compraItem.ProdutoId);
            return View(compraItem);
        }

        // POST: CompraItems/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("CompraItemId,CompraId,ProdutoId,Quantidade,Unitario")] CompraItem compraItem)
        {
            if (id != compraItem.CompraItemId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(compraItem);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CompraItemExists(compraItem.CompraItemId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CompraId"] = new SelectList(_context.Compras, "CompraId", "Nota", compraItem.CompraId);
            ViewData["ProdutoId"] = new SelectList(_context.Produtos, "ProdutoId", "Nome", compraItem.ProdutoId);
            return View(compraItem);
        }

        // GET: CompraItems/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null || _context.CompraItens == null)
            {
                return NotFound();
            }

            var compraItem = await _context.CompraItens
                .Include(c => c.Compra)
                .Include(c => c.Produto)
                .FirstOrDefaultAsync(m => m.CompraItemId == id);
            if (compraItem == null)
            {
                return NotFound();
            }

            return View(compraItem);
        }

        // POST: CompraItems/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            if (_context.CompraItens == null)
            {
                return Problem("Entity set 'SprintContext.CompraItens'  is null.");
            }
            var compraItem = await _context.CompraItens.FindAsync(id);
            if (compraItem != null)
            {
                _context.CompraItens.Remove(compraItem);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CompraItemExists(Guid id)
        {
          return (_context.CompraItens?.Any(e => e.CompraItemId == id)).GetValueOrDefault();
        }
    }
}

Somativa/Somativa/Controllers/ComprasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Somativa.Data;
using Somativa.Models;

namespace Somativa.Controllers
{
	[Authorize(Roles = "Admin,Operador")]
	public class ComprasController : Controller
    {
        private readonly SprintContext _context;

        public ComprasController(SprintContext context)
        {
            _context = context;
        }

        // GET: Compras
        public async Task<IActionResult> Index()
        {
              return _context.Compras != null ? 
                          View(await _context.Compras.ToListAsync()) :
                          Problem("Entity set 'SprintContext.Compras'  is null.");
        }

        // GET: Compras/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null || _context.Compras == null)
            {
                return NotFound();
            }

            var compra = await _context.Compras
                .FirstOrDefaultAsync(m => m.CompraId == id);
            if (compra == null)
            {
                return NotFound();
            }

            return View(compra);
        }

        // GET: Compras/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Compras/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CompraId,Nota,DataHora")] Compra compra)
        {
            if (ModelState.IsValid)
            {
                compra.CompraId = Guid.NewGuid();
                _context.Add(compra);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(compra);
        }

        // GET: Compras/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null || _context.Compras == null)
            {
                return NotFound();
            }

            var compra = await _context.Compras.FindAsync(id);
            if (compra == null)
            {
                return NotFound();
            }
            return View(compra);
        }

        // POST: Compras/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("CompraId,Nota,DataHora")] Compra compra)
        {
            if (id != compra.CompraId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(compra);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CompraExists(compra.CompraId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(compra);
        }

        // GET: Compras/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null || _context.Compras == null)
            {
                return NotFound();
            }

            var compra = await _context.Compras
                .FirstOrDefaultAsync(m => m.CompraId == id);
            if (compra == null)
            {
                return NotFound();
            }

            return View(compra);
        }

        // POST: Compras/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            if (_context.Compras == null)
            {
                return Problem("Entity set 'SprintContext.Compras'  is null.");
            }
            var compra = await _context.Compras.FindAsync(id);
            if (compra != null)
            {
                _context.Compras.Remove(compra);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CompraExists(Guid id)
        {
          return (_context.Compras?.Any(e => e.CompraId == id)).GetValueOrDefault();
        }
    }
}

Somativa/Somativa/Views/CompraItems/Create.cshtml
@model Somativa.Models.CompraItem

@{
    ViewData["Title"] = "Create";
    var CompraIdAux = ViewData["CompraId"];
}

<div class="row d-flex justify-content-center my-3">
    <div class="rounded conted py-3 col-10 col-sm-6">
        <h4 class="text-center">Adicionar Item da Compra</h4>

        <div class="row d-flex justify-content-center m-2 m-sm-0">
            <div class="col-md-10">
                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="CompraId" class="control-label textin"></label>
                        <input asp-for="CompraId" value="@ViewBag.CompraId" class="form-control rounded-pill border-1 my-2" readonly  />
                    </div>
                    <div class="form-group">
                        <label asp-for="ProdutoId" class="control-label textin"></label>
                        <select asp-for="ProdutoId" class="form-control rounded-pill border-1 my-2" asp-items="ViewBag.ProdutoId"></select>
                    </div>
                    <div class="form-group">
                        <label asp-for="Quantidade" class="control-label textin"></label>
                        <input asp-for="Quantidade" class="form-control rounded-pill border-1 my-2" />
                        <span asp-validation-for="Quantidade" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Unitario" class="control-label textin"></label>
                        <input asp-for="Unitario" type="number" class="form-control rounded-pill border-1 my-2" />
                        <span asp-validation-for="Unitario" class="text-danger"></span>
                    </div>
                    <div class="form-group d-flex justify-content-center">
                        <button type="submit" value="Create" class="adidi rounded-pill me-2 my-2">Cadastrar</button>
                        <a asp-action="Index" asp-route-id="@CompraIdAux" class="btn volt rounded-pill my-2">Cancelar</a>
                    </div>
                </form>
            </div>
        </div>

    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Somativa/Somativa/Views/CompraItems/Delete.cshtml
@model Somativa.Models.CompraItem

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CompraItem</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Compra)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Compra.CompraId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Produto)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Produto.ProdutoId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Quantidade)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Quantidade)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Unitario)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Unitario)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="CompraItemId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Somativa/Somativa/Views/CompraItems/Details.cshtml
@model Somativa.Models.CompraItem

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>CompraItem</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Compra)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Compra.CompraId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Produto)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Produto.ProdutoId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Quantidade)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Quantidade)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Unitario)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Unitario)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.CompraItemId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Somativa/Somativa/Views/CompraItems/Edit.cshtml
@model Somativa.Models.CompraItem

@{
    ViewData["Title"] = "Edit";
}
<div class="row d-flex justify-content-center my-3">
    <div class="rounded conted py-3 col-10 col-sm-6">
        <h4 class="text-center">Atualizar Item da Compra</h4>

        <div class="row d-flex justify-content-center m-2 m-sm-0">
            <div class="col-md-10">
                <form asp-action="Edit">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="CompraItemId" />
                    <div class="form-group">
                        <label asp-for="CompraId" class="control-label textin"></label>
                        <select asp-for="CompraId" class="form-control rounded-pill border-1 my-2" asp-items="ViewBag.CompraId"></select>
                        <span asp-validation-for="CompraId" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="ProdutoId" class="control-label textin"></label>
                        <select asp-for="ProdutoId" class="form-control rounded-pill border-1 my-2" asp-items="ViewBag.ProdutoId"></select>
                        <span asp-validation-for="ProdutoId" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Quantidade" class="control-label textin"></label>
                        <input asp-for="Quantidade" class="form-control rounded-pill border-1 my-2" />
                        <span asp-validation-for="Quantidade" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Unitario" class="control-label textin"></label>
                        <input asp-for="Unitario" type="number" class="form-control rounded-pill border-1 my-2" />
                        <span asp-validation-for="Unitario" class="text-danger"></span>
                    </div>
                    <div class="form-group d-flex justify-content-center">
                        <button type="submit" value="Save" class="adidi rounded-pill me-2 my-2">Salvar</button>
                        <a asp-action="Index" asp-route-id="@ViewBag.CompraId" class="btn volt rounded-pill my-2">Cancelar</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Somativa/Somativa/Views/CompraItems/Index.cshtml
@model IEnumerable<Somativa.Models.CompraItem>

@{
    ViewData["Title"] = "Index";
}

<h1 class="textocima">Itens da Compra</h1>

<p>
    <a asp-action="Create" asp-route-id="@ViewBag.CompraId" class="btn adidi rounded-pill me-3">Adicionar</a>
    <a asp-action="Index" asp-controller="Compras" class="volt rounded-circle pt-1 pb-2 px-2">
        <svg bootstrap-icon="ArrowLeft" width="24" height="24" class="text-dark"></svg>
    </a>
</p>

<table class="table">
    <thead>
        <tr class="d-flex">
            <th class="border-0 d-none d-sm-table-cell col-2"></th>
            <th class="col-3">
                @Html.DisplayNameFor(model => model.Compra)
            </th>
            <th class="col-3">
                @Html.DisplayNameFor(model => model.Produto)
            </th>
            <th class="col-3 col-sm-2">
                @Html.DisplayNameFor(model => model.Quantidade)
            </th>
            <th class="col-3 col-sm-2">
                @Html.DisplayNameFor(model => model.Unitario)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr class="d-flex">
                <td class="d-none d-sm-table-cell col-2">
                    <a asp-action="Edit" asp-route-id="@item.CompraItemId" class="text-decoration-none">
                        <svg bootstrap-icon="PencilSquare" width="24" height="24" class="text-dark me-2 my-2"></svg>
                    </a>
                    <a data-bs-toggle="modal" data-bs-target="#ModalTrash-@item.CompraItemId">
                        <svg bootstrap-icon="Trash" width="24" height="24" class="text-dark me-2 my-2"></svg>
                    </a>
                </td>
                <td class="col-3">
                    @Html.DisplayFor(modelItem => item.Compra.Nota)
                </td>
                <td class="col-3">
                    @Html.DisplayFor(modelItem => item.Produto.Nome)
                </td>
                <td class="col-3 col-sm-2">
                    @Html.DisplayFor(modelItem => item.Quantidade)
                </td>
                <td class="col-3 col-sm-2">
                    @Html.DisplayFor(modelItem => item.Unitario)
                </td>
            </tr>
            <tr class="d-sm-none w-100 d-flex ">
                <td class="col-6 d-flex justify-content-center">
                    <a asp-action="Edit" asp-route-id="@item.CompraItemId">
                        <svg bootstrap-icon="PencilSquare" width="24" height="24" class="text-dark me-2 my-2"></svg>
                    </a>
                </td>
                <td class="col-6 pe-0 d-flex justify-content-center ">
                    <a data-bs-toggle="modal" data-bs-target="#ModalTrash-@item.CompraItemId">
                        <svg bootstrap-icon="Trash" width="24" height="24" class="text-dark me-2 my-2"></svg>
                    </a>
                </td>
            </tr>
            <div class="modal fade" id="ModalTrash-@item.CompraItemId" data-bs-keyboard="false" aria-labelledby="staticBackdropLabel" tabindex="-1" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered">
                    <div class="modal-content">
                        <div class="modal-header justify-content-center border-0">
                            <h5 class="modal-title text-center volt px-5 py-1 fs">Apagar</h5>
                        </div>
                        <div class="modal-body text-center border-0">
                            <p class="text-dark fs-3 fst-normal">Tem certeza que deseja apagar dados da @Html.DisplayFor(modelItem => item.Compra.Nota)?</p>
                        </div>
                        <div class="modal-footer d-flex justify-content-center border-0">
                            <form asp-action="Delete" asp-route-id="@item.CompraItemId" class="me-5">
                                <input type="hidden" asp-for="@item.CompraItemId" />
                                <button type="submit" class="btn apag text-white">Deletar</button>
                            </form>
                            <button data-bs-dismiss="modal" class="btn volt2 text-white">Cancelar</button>
                        </div>
                    </div>
                </div>
            </div>
        }
    </tbody>
</table>