Somativa/Somativa/Controllers/RelatorioController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NuGet.Common;
using Somativa.Data;
using Somativa.Models;
using System.Security.Policy;

namespace Somativa.Controllers
{
    [Authorize(Roles = "Admin,Gerente")]
    public class RelatorioController : Controller
    {
        private readonly SprintContext _context;

        public RelatorioController(SprintContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> RelatProd()
        {
            var prod = await _context.Produtos.Include(c => c.Categoria).ToListAsync();
            ViewData["Categ"] = await _context.Categorias.ToListAsync();
            
            return View(prod);
        }

        public async Task<IActionResult> SearchProd(Guid inCategoria, string inNome)
        {
			var prod = await _context.Produtos.Include(c => c.Categoria).ToListAsync();

            if (inNome != null) 
            {
				inNome = inNome.Trim().ToUpper();
                prod = prod.Where(i => i.Nome.ToUpper().Contains(inNome)).ToList();
			}

            if (!inCategoria.ToString().Equals("00000000-0000-0000-0000-000000000000"))
            {
                prod = prod.Where(i => i.CategoriaId == inCategoria).ToList();
            }

			ViewData["Categ"] = await _context.Categorias.ToListAsync();
			return View("RelatProd", prod);
        }

		public async Task<IActionResult> RelatMov()
        {
            var mov = await MovimentacaoList.getList(_context);
            ViewData["Produtos"] =  await _context.Produtos.ToListAsync();

			return View(mov);
        }

        public async Task<IActionResult> SearchMov(DateTime? inDataIni, DateTime? inDataFim, int inTipo, string inProduto)
        {
			var mov = await MovimentacaoList.getList(_context);
			ViewData["Produtos"] = await _context.Produtos.ToListAsync();

            if (inDataIni != null) mov = mov.Where(i => i.DataHora >= inDataIni).ToList();
			if (inDataFim != null) mov = mov.Where(i => i.DataHora <= inDataFim).ToList();

            if (inTipo == 1) mov = mov.Where(i => i.TipoMovimentacao.Equals("Entrada")).ToList();
			if (inTipo == 2) mov = mov.Where(i => i.TipoMovimentacao.Equals("Saída")).ToList();

            if (!inProduto.ToString().Equals("Todos"))
                mov = mov.Where(i => i.Produto.Equals(inProduto)).ToList();

			return View("RelatMov", mov);
        }

        public IActionResult GetImage2(string fileName) 
        {
           
            var imgPath = Path.Combine("../MinhasImagens", fileName );
			if (System.IO.File.Exists(imgPath))
            {
				var imageBytes = System.IO.File.ReadAllBytes(imgPath);
				return File(imageBytes, "image/png");
			}
			return NotFound();
		}

		public IActionResult GetImage(string imageName)
		{
			string applicationPath = AppDomain.CurrentDomain.BaseDirectory;
            string teste = System.IO.Directory.GetCurrentDirectory();
			//var imagePath = Path.Combine(applicationPath + "Somativa\\MinhasImagens", imageName);
		
			var imagePath = teste + "\\minhasimagens\\imagem.png";

			if (System.IO.File.Exists(imagePath))
			{
				var imageBytes = System.IO.File.ReadAllBytes(imagePath);
				return File(imageBytes, "image/png");
			}

			return NotFound();
		}



	}
}

Somativa/Somativa/Views/Relatorio/RelatMov.cshtml
@model IEnumerable<Somativa.Models.Movimentacao>

@{
    ViewData["Title"] = "RelatMov";
    var prod = ViewData["Produtos"] as List<Produto>;
    prod.Insert(0, new Produto { ProdutoId = new Guid(), Nome = "Todos" });
}

<h1 class="my-5">Relatório de Movimetação</h1>

<form class="my-3">
    <div class="mt-3 mb-3 d-flex flex-column align-items-center w-100">
        <div class="d-flex flex-column flex-sm-row align-items-center my-2 w-100">
            <label class="fs-5 col-12 col-sm-2">Data início</label>
            <input name="inDataIni" type="date" class="col-12 col-sm-4 ms-3 me-3 px-3 border-1 toptop" />
            <label class="fs-5 col-12 col-sm-2">Data fim</label>
            <input name="inDataFim" type="date" class="col-12 col-sm-4 ms-3 me-3 px-3 border-1 toptop" />
        </div>
        <div class="d-flex flex-column flex-sm-row align-items-center my-2 w-100">
            <label class="fs-5 col-12 col-sm-2">Tipo de movimentação</label>
            <select name="inTipo" class="col-12 col-sm-4 ms-3 me-3 px-3 border-1 toptop">
                <option value="0">Todos</option>
                <option value="1">Entradas</option>
                <option value="2">Saídas</option>
            </select>

            <label class="fs-5 col-12 col-sm-2">Produto</label>
            <select name="inProduto" class="ms-3 me-3 px-3 border-1 toptop col-12 col-sm-4">
                @foreach (var item in prod)
                {
                    <option value="@item.Nome">@item.Nome</option>
                }
            </select>
        </div>
        <button asp-action="SearchMov" class="btn btn-success col-2">Filtrar</button>
    </div>
</form>


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nota)
            </th>
            <th class="d-none d-sm-table-cell">
                @Html.DisplayNameFor(model => model.DataHora)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TipoMovimentacao)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Produto)
            </th>
            <th class="d-none d-sm-table-cell">
                @Html.DisplayNameFor(model => model.Quantidade)
            </th>
            <th class="d-none d-sm-table-cell">
                @Html.DisplayNameFor(model => model.Unitario)
            </th>
            <th class="d-sm-none"></th>

        </tr>
    </thead>
    <tbody >
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nota)
                </td>
                <td class="d-none d-sm-table-cell">
                    @Html.DisplayFor(modelItem => item.DataHora)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TipoMovimentacao)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Produto)
                </td>
                <td class="d-none d-sm-table-cell">
                    @Html.DisplayFor(modelItem => item.Quantidade)
                </td>
                <td class="d-none d-sm-table-cell">
                    @Html.DisplayFor(modelItem => item.Unitario)
                </td>
                <td class="w-100 d-flex justify-content-center">
                    <a data-bs-toggle="modal" data-bs-target="#ModalPlus-@item.Nota">
                        <svg bootstrap-icon="Plus" width="24" height="24" class="text-dark me-2 my-2"></svg>
                    </a>
                </td>
            </tr>
            <div class="modal fade" id="ModalPlus-@item.Nota" data-bs-keyboard="false" aria-labelledby="staticBackdropLabel" tabindex="-1" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered">
                    <div class="modal-content">
                        <div class="modal-header justify-content-center border-0">
                            <h5 class="modal-title text-center volt px-5 py-1 fs">Detalhes</h5>
                        </div>
                        <div class="modal-body text-center border-0">
                            <p class="fw-bold">Note:</p>
                            <div class="my-2">@Html.DisplayFor(modelItem => item.Nota)</div>
                            <p class="fw-bold">Data e Hora:</p>
                            <div class="my-2">@Html.DisplayFor(modelItem => item.DataHora)</div>
                            <p class="fw-bold">Tipo de Movimentação:</p>
                            <div class="my-2">@Html.DisplayFor(modelItem => item.TipoMovimentacao)</div>
                            <p class="fw-bold">Produto::</p>
                            <div class="my-2">@Html.DisplayFor(modelItem => item.Produto)</div>
                            <p class="fw-bold">Quantidade:</p>
                            <div class="my-2">@Html.DisplayFor(modelItem => item.Quantidade)</div>
                            <p class="fw-bold">Preço Unitário:</p>
                            <div class="my-2">@Html.DisplayFor(modelItem => item.Unitario)</div>
                        </div>
                        <div class="modal-footer d-flex justify-content-center border-0">
                            <button data-bs-dismiss="modal" class="btn volt2 text-white">Fechar</button>
                        </div>
                    </div>
                </div>
            </div>
        }
    </tbody>
</table>

Somativa/Somativa/Views/Relatorio/RelatProd.cshtml
@model IEnumerable<Somativa.Models.Produto>

@{
    ViewData["Title"] = "RelatProd";

    List<Categoria> categorias = new List<Categoria>();
    categorias.Add(new Categoria { CategoriaId = new Guid(), Nome = "Todas" });
    var categ = ViewData["Categ"] as List<Categoria>;

    foreach (var item in categ)
    {
        categorias.Add(new Categoria { CategoriaId = item.CategoriaId, Nome = item.Nome });
    }
}

<h1 class="my-5">Relatório de Produtos</h1>

<!--
<img src="@Url.Action("GetImage", "Relatorio", new { imageName = "imagem.png" })" alt="Descrição da imagem">
-->
<form class="my-3">
    <div id="filtros" class="d-flex row justify-content-center">
        <div class="col-12 col-sm-6 d-flex my-2 my-sm-0">
            <label class="fs-5 ">Categoria</label>
            <select name="inCategoria" class="ms-3 me-3 px-3 border-1 w-100 toptop">
                @foreach (var item in categorias)
                {
                    <option value="@item.CategoriaId">@item.Nome</option>
                }
            </select>
        </div>
        <div class="col-12 col-sm-6 d-flex my-2 my-sm-0">    
            <label class="fs-5">Nome</label>
            <input name="inNome" type="text" class="ms-3 me-3 w-100" />
            <button asp-action="SearchProd" class="btn btn-success d-none d-sm-block">Filtrar</button>
        </div>
        <button asp-action="SearchProd" class="btn btn-success col-2 d-sm-none">Filtrar</button>
    </div>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Categoria.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Estoque)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Preco)
            </th>

        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nome)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Categoria.Nome)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Estoque)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Preco)
                </td>

            </tr>
        }
    </tbody>
</table>